<?php
defined('BASEPATH') OR exit('No direct script access allowed');
class Banners extends CI_Controller {
    public function __construct(){ parent::__construct(); $this->auth_admin(); }
    private function auth_admin(){ if($this->session->userdata('role')!=='admin') redirect('login'); }
    public function index(){ $this->db->order_by('sort_order','asc'); $data['banners']=$this->db->get('banners')->result(); $this->load->view('admin/partials/header'); $this->load->view('admin/banners/index',$data); $this->load->view('admin/partials/footer'); }
    public function create(){ if($this->input->method()==='post'){ $title=$this->input->post('title',TRUE); $image=NULL; if(!empty($_FILES['image']['name'])){ $config=['upload_path'=>UPLOAD_PATH_PRODUCTS,'allowed_types'=>ALLOWED_IMAGE_TYPES,'max_size'=>2048]; $this->load->library('upload',$config); if($this->upload->do_upload('image')) $image='/public/assets/img/uploads/'.$this->upload->data('file_name'); } $this->db->insert('banners',[ 'title'=>$title,'image'=>$image,'link'=>$this->input->post('link',TRUE),'is_active'=>$this->input->post('is_active')?1:0,'sort_order'=>$this->input->post('sort_order')?:0 ]); return redirect('admin/banners'); } $this->load->view('admin/partials/header'); $this->load->view('admin/banners/create'); $this->load->view('admin/partials/footer'); }
    public function edit($id){ $b=$this->db->get_where('banners',['id'=>$id])->row(); if(!$b) show_404(); if($this->input->method()==='post'){ $data=[ 'title'=>$this->input->post('title',TRUE),'link'=>$this->input->post('link',TRUE),'is_active'=>$this->input->post('is_active')?1:0,'sort_order'=>$this->input->post('sort_order')?:0 ]; if(!empty($_FILES['image']['name'])){ $config=['upload_path'=>UPLOAD_PATH_PRODUCTS,'allowed_types'=>ALLOWED_IMAGE_TYPES,'max_size'=>2048]; $this->load->library('upload',$config); if($this->upload->do_upload('image')) $data['image']='/public/assets/img/uploads/'.$this->upload->data('file_name'); } $this->db->update('banners',$data,['id'=>$id]); return redirect('admin/banners'); } $data['banner']=$b; $this->load->view('admin/partials/header'); $this->load->view('admin/banners/edit',$data); $this->load->view('admin/partials/footer'); }
    public function delete($id){ $this->db->delete('banners',['id'=>$id]); redirect('admin/banners'); }
}
